### ISSUE TITLE
Don't wrap text in codeblocks

### ISSUE THREAD

**Issue by opsyne** [bouncepaw/mycorrhiza#183]
Currently, codeblocks in hyphae have wrapped text, due to the following CSS rules

```css
article pre.codeblock {
  /* ... */
  white-space: pre-wrap;
  /* ... */
}
```

It's not difficult to change since I already use a script to add custom styles, but since most sites seem to use `white-space: pre`, I think `pre` would make a better default than `pre-wrap`.

I figured I'd propose the change before making a PR since it might've been done for a reason.
